services:
  imgen:
    container_name: text2image
    build: .
    restart: unless-stopped
    runtime: nvidia
    ports:
      - "8010:8010"
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - HF_HOME=/root/.cache/huggingface
      - NVIDIA_VISIBLE_DEVICES=all
      - FLUX_DEFAULT_STEPS=4
      - FLUX_DEFAULT_GUIDANCE=1.0
    volumes:
      - hf_cache:/root/.cache/huggingface 
    

volumes:
  hf_cache: 
